# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration
#
[remote.github]
owner = "florian-sanders"
repo = "zed-stylelint"

[changelog]
header = "# Changelog"
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% macro print_commit(commit) -%}
    - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
        {% if commit.breaking %}[**breaking**] {% endif %}\
        {{ commit.message | upper_first }} - \
        ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))\
        {% if commit.remote.username %} by @{{ commit.remote.username }}{%- endif %}\
        {% for footer in commit.footers %}
          {{ footer.token }}
        {% endfor %}
{% endmacro -%}

{% if version %}\
    {% if previous.version %}\
        ## [{{ version | trim_start_matches(pat="v") }}]\
          ({{ self::remote_url() }}/compare/{{ previous.version }}..{{ version }}) - {{ timestamp | date(format="%Y-%m-%d") }}
    {% else %}\
        ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
    {% endif %}\
{% else %}\
    ## [unreleased]
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits
    | filter(attribute="scope")
    | sort(attribute="scope") %}
        {{ self::print_commit(commit=commit) }}
    {%- endfor %}
    {% for commit in commits %}
        {%- if not commit.scope -%}
            {{ self::print_commit(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor -%}
{%- if github -%}
{% if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
  ## New Contributors ❤️
{% endif %}\
{% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
  * @{{ contributor.username }} made their first contribution
    {%- if contributor.pr_number %} in \
      [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }}) \
    {%- endif %}
{%- endfor -%}
{%- endif %}
"""
footer = ""
trim = true
render_always = true
postprocessors = [
  # Replace the placeholder `<REPO>` with a URL.
  { pattern = '<REPO>', replace = "https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}" },
]

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_preprocessors = [
  # Replace issue numbers with link templates to be updated in `changelog.postprocessors`.
  { pattern = "#(\\d+)", href = "https://github.com/orhun/git-cliff/issues/$1" },
]
protect_breaking_commits = false
commit_parsers = [
  { message = '\[skip changelog\]', skip = true },
  { message = "^feat", group = "✨ Features" },
  { message = "^fix", group = "🐛 Bug Fixes" },
  { message = "^chore", group = "🔧 Chores", skip = true },
  { message = "^docs?", group = "📚 Documentation" },
  { message = "^refactor", group = "♻️ Refactoring", skip = true },
  { message = "^perf", group = "⚡️ Performance" },
  { message = "^test", group = "✅ Tests" },
  { message = "^ci", group = "🤖 CI" },
  { message = "^build", group = "🛠 Build System" },
  { message = ".*", group = "Other" },
]
filter_commits = false
link_parsers = [
  { pattern = "(?P<id>[a-f0-9]{7,40})", href = "https://github.com/florian-sanders/zed-stylelint/commit/{{id}}" },
]
use_branch_tags = false
topo_order = false
topo_order_commits = true
sort_commits = "oldest"
recurse_submodules = false
